# Generated by Django 4.1.2 on 2022-10-31 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_manager_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('division', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_manager_name', models.CharField(max_length=50)),
                ('district_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.districtmanager')),
                ('store', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='main.store')),
            ],
        ),
        migrations.AddField(
            model_name='districtmanager',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.store'),
        ),
    ]
