# Generated by Django 4.1.2 on 2022-10-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('division', models.IntegerField()),
                ('district_manager', models.CharField(max_length=50)),
                ('city_manager', models.CharField(max_length=50)),
                ('weekday_opening', models.CharField(max_length=10)),
                ('weekday_closing', models.CharField(max_length=10)),
                ('sat_opening', models.CharField(max_length=10)),
                ('sat_closing', models.CharField(max_length=10)),
                ('sun_opening', models.CharField(max_length=10)),
                ('sun_closing', models.CharField(max_length=10)),
            ],
        ),
    ]
